var foodArray = [
  'pizza', 'a burger', 'a pasta', 'spaghetti', 'a sandwich', 'a candy', 'a cake', 'rice'
];
var randomNumberFood = Math.floor(Math.random()*foodArray.length);
var ingredientArray = [
  'ketchup', 'milk', 'cheese', 'tile cutter battipav basic 2060 6', 'a candy', 'mayo', 'salt', 'pepper', 'a fish', 'air', 'poop', 'electricity', 'a tomato', 'a cucumber', 'a knife', 'meat', 'spaghetti', 'memes', 'dark energy'
];
var randomNumberIngredient = Math.floor(Math.random()*ingredientArray.length);
var randomNumberIngredient2 = Math.floor(Math.random()*ingredientArray.length);
var randomNumberIngredient3 = Math.floor(Math.random()*ingredientArray.length);
var randomNumberIngredient4 = Math.floor(Math.random()*ingredientArray.length);

var textArray1 = [
    'You',
    'JFK',
    'Yo Mama',
    'A discord mod',
    'Newton',
    'Einstein',
'A duck',
'amogus',
'Kanye West',
'Maxwell',
'Gaben',
'sussy baka',
'hat girl',
'Rick Astley',
'Fish',
'goofy ahh man',
'School teacher',
'Trollface',
'Karen',
'Kyle',
  'Microsoft',
'Spongebob',
'Попытерка',
'Mojang',
'A headcrab',
'Floppa',
'A virgin(not oil)',
'Ohioman',
'GLaDOS',
'Doomguy',
'Yo dad',
'Chef',
'An alien',
'An imposter',
'A crewmate',
'A bro',
'QuantumV3',
'A scientist',
'Cave Johnson',
'Harry Potter',
'Yo classmate',
'PE teacher',
'Gigachad',
'Chad',
'A clown',
'Guy',
'Girl',
'unknown',
'gamer girl uwu',
'Your cat',
'Xxx_ALEXPRO228COOL_xxX',
'Me',
'Mr. Beast!!!',
'Peppino',
'Bebrick',
'Gordon Freeman',
'An italian',
'anonymous73852',
'idfsjfgihjgdfgj',
'hi'
];
var randomNumber1_1 = Math.floor(Math.random()*textArray1.length);

var textArray2 = [
    'cooked ' + foodArray[randomNumberFood] + " out of " + " " + ingredientArray[randomNumberIngredient] + ", " + ingredientArray[randomNumberIngredient2] + ", " + ingredientArray[randomNumberIngredient3] + ", and " + ingredientArray[randomNumberIngredient4],
    'played Among Us',
    'created the first Windows PC',
    'asked who Joe is',
    'became a discord mod',
    'did a crime using a sponge',
    'created the first Ikea',
  'was not an impostor',
'was an impostor',
'just pooped',
'flied using the wooden plate',
'bought a burger',
'has bought a new game in steam',
'called the emergency meeting',
'meowed',
'said uwu',
'played OldGuns',
'launched an orbital station',
'created a clan',
'started a new livestream',
'uploaded a new video',
'unlocked a new achievment',
'exploded an explosive bomb named explosive bomb named explosive',
'got rickrolled',
'searched dqw4w and pressed feeling lucky',
'got stickbugged',
'found a bug',
'downloaded a virus',
'did something',
'example text',
'breathed',
'got scammed',
'lost a game',
'won a game',
'won a lottery',
  'waited for half-life 3',
'is sus',
'forgor his charger',
'was born',
'shared his opinion on the internet',
'coded a game',
'remixed a song',
'is sleeping',
'il a mangé une baguette et est devenu français',
'thought school was easy',
'got an A+',
'became succesful business man',
'scammed someone',
'turned temperature up',
'donated 1000$ to charity',
'got a F-',
'drank tea',
'died',
  'asked chat gpt what the hell is wrong with these phrases',
'was ejected',
'created a new ai',
'built a city',
'got blocked by an adblocker',
'yelled so loud that the glass broke',
'said bruh',
'started a war',
'created a new month',
'learned a new dance',
'fired his boss',
'committed war crimes',
'bought 2$ on the price of 1$',
'bought 1$ on the price of 2$',
'fed his cat',
'got blocked on twitter',
'turned into a furry',
'was arrested',
'yelled at ' + textArray1[randomNumber1_1],
'declared his love to '  + textArray1[randomNumber1_1],
'just called ' + textArray1[randomNumber1_1],
'created a new account',
'traveled to xen',
'committed cascade resonance',
'found a jojo reference',
'googled the scientific name of the pig and died',
  "created the first Atomic Bomb",
'mixed cola and mentos'
];
var randomNumber2 = Math.floor(Math.random()*textArray2.length);
document.getElementById("action").innerHTML = textArray2[randomNumber2];

/*var textArray3 = [
    '0001',
    '1969',
    '2420',
    '1842',
    '1392',
    '1952',
  '2020',
'2077',
'the year 1000',
'the year 2000',
'the year 69',
'1420',
'9999',
'3493',
'7304',
'2007',
'2012',
'the far future'
];*/
/*var randomNumber3 = Math.floor(Math.random()*textArray3.length);*/
var randomNumber3 = (Math.random() * (2050 - 0001 + 1) ) << 0

document.getElementById("year").innerHTML = "" + randomNumber3;
var textArray4 = [
  'on the first of april',
'on new year',
'on halloween',
'on monday',
'on tuesday',
'on wednesday(REFERENCE??????????)',
'on thursday',
'on friday',
'on saturday',
'on sunday',
'today',
'yesterday',
'29th of february',
'every day',
'last week',
'on the 1st of hgfhdughdfiughdfigdfary',
'in october',
'in november',
'in december',
'in august',
'in april',
'in march',
'in september',
'in may',
'on the 7th of july',
'in june',
'in january',
'in february'
];
var randomNumber4 = Math.floor(Math.random()*textArray4.length);
document.getElementById("date").innerHTML = textArray4[randomNumber4];


